server:
  port: 7010
spring:
  application:
    name: images


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


accessKey: Y9mOOnlwXSocxJtntYqQIR6k7Dwf_n3Icsn5Ep8e    #访问秘钥
secretKey: 6GQLTIErXis_YicJ3h7gHBp1OGqoawQpRk7ZKikB    #授权秘钥
bucket: cxp                                            #存储空间名称
domain:  http://q2wh9mmyk.bkt.clouddn.com/              #外链域名


UserPhotoLocalPath: C:/cxp_cxp_cxp/cxp_studio/nginx-1.14.2/html/TianGou/resource/userPhoto/
CommodityPhotoLocalPath: C:/cxp_cxp_cxp/cxp_studio/nginx-1.14.2/html/TianGou/resource/userPhoto/
CommodityVideoLocalPath: C:/cxp_cxp_cxp/cxp_studio/nginx-1.14.2/html/TianGou/resource/userPhoto/

userPhotoUriPrifix: /TianGou/resource/userPhoto/
commodityPhotoUriPrifix: /TianGou/resource/commodity/images/
commodityVideoUriPrifix: /TianGou/resource/commodity/video/