server:
  port: 7010

spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka


zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options,token
